name: nix-check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  nix-check:
    name: nix-check
    runs-on: ubuntu-latest

    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Alejandra
        uses: luisnquin/setup-alejandra@v1.0.0
      - name: Check formatting
        run: alejandra --check */**/*.nix
      - name: Install nix action
        uses: cachix/install-nix-action@v20
        with:
          install_url: https://nixos.org/nix/install
          extra_nix_config: |
            auto-optimise-store = true
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            experimental-features = nix-command flakes
      - name: Flake check
        run: nix flake check
