name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  nix:
    name: check and build
    runs-on: ubuntu-latest

    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Install nix action
        uses: cachix/install-nix-action@v20
        with:
          install_url: https://nixos.org/nix/install
          extra_nix_config: |
            auto-optimise-store = true
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            experimental-features = nix-command flakes
      - name: Flake check (includes tests, clippy, rustfmt)
        run: nix flake check -L
      - name: Build package
        run: nix build
